---

dist: xenial
language: python
python:
  - "2.7"
  - "3.6"
  - "3.7"

install:
  - make build VENV=${VIRTUAL_ENV}
  - pip install -r dev-requirements.txt

script:
  - make lint VENV=${VIRTUAL_ENV}
  - make unittest VENV=${VIRTUAL_ENV}
  - make test VENV=${VIRTUAL_ENV}
